-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgtgI2GWQ3mx3hvDp2
UcJ2CGW5wcwGYW4ANy87rHUEZaqgCgYIKoZIzj0DAQehRANCAAQNbgrSodKNwRcK
pwFXgneThQR+9IiuIdBlACP+Ele5BGOGOwHSAkYFypKqfCpa1lkCnpf+cZ2UQm94
iE4XBDgs
-----END PRIVATE KEY-----